[project]
name = "polygon-pavilion"
version = "0.1.0"
requires-python = ">=3.9,<3.10"
dependencies = ["rhino-stubs-typed~=8.20.25157"]

[tool.pyright]
typeCheckingMode = "strict"
extraPaths = ["src"]

[tool.ruff.lint]
extend-select = ["N", "I", "T20", "RUF", "SLF", "INP", "ASYNC"]
